{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "0c424920_310ef6df",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 2679
      },
      "writtenOn": "2023-11-14T07:59:35Z",
      "side": 1,
      "message": "Gating failed:\nhttps://logs.onap.org/onap-integration/gating//136194-3/infrastructure-healthcheck/k8s-teardown/k8s-teardown/pod-onap-sdc-wfd-be-wwzn6-sdc-wfd-be-job-logs.html\n```\nTraceback (most recent call last):\n  File \"/usr/local/bin/cqlsh\", line 129, in \n    from cassandra.cluster import Cluster\n  File \"/usr/local/lib/python2.7/site-packages/cassandra/cluster.py\", line 24, in \n    from concurrent.futures import ThreadPoolExecutor, FIRST_COMPLETED, wait as wait_futures\nImportError: No module named concurrent.futures\nTraceback (most recent call last):\n  File \"/usr/local/bin/cqlsh\", line 129, in \n    from cassandra.cluster import Cluster\n  File \"/usr/local/lib/python2.7/site-packages/cassandra/cluster.py\", line 24, in \n    from concurrent.futures import ThreadPoolExecutor, FIRST_COMPLETED, wait as wait_futures\nImportError: No module named concurrent.futures\n\n```",
      "revId": "8638fea39ca5d70a47baac6068c84beae615045a",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "3b741441_0aa0b0c2",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 2679
      },
      "writtenOn": "2023-11-14T08:00:25Z",
      "side": 1,
      "message": "Possibly related to the fact, that we use cassandra 4.0.x in Montreal ?",
      "revId": "8638fea39ca5d70a47baac6068c84beae615045a",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a"
    }
  ]
}